name: AvatarDonation
version: '${project.version}'
api-version: 1.13
folia-supported: true
authors: [aglerr, starfruit2210]
main: me.aglerr.donations.DonationPlugin
softdepend:
  - SkinsRestorer
  - PlaceholderAPI
libraries:
  - dev.jorel:commandapi-paper-shade:11.0.0
